### ISSUE TITLE
get-leaf-location example not working

### ISSUE THREAD

**Issue by johnty** [gboudreau/nissan-connect-php#17]
thanks for the library!

the get location example doesn't seem to work for some reason. the other tests run fine.

here's the error:

```
Prepare Session
Login...
request_location
ERROR:pycarwings2.pycarwings2:carwings error -5256: [MyCarFinder] API call error
Traceback (most recent call last):
  File "get-leaf-location.py", line 32, in <module>
    result_key = l.request_location()
  File "C:\Python27\lib\site-packages\pycarwings2\pycarwings2.py", line 415, in request_location
    "UserId": self.session.gdc_user_id, # this userid is the 'gdc' userid
  File "C:\Python27\lib\site-packages\pycarwings2\pycarwings2.py", line 101, in _request_with_retry
    ret = self._request(endpoint, params)
  File "C:\Python27\lib\site-packages\pycarwings2\pycarwings2.py", line 141, in _request
    raise CarwingsError
pycarwings2.pycarwings2.CarwingsError
```

**Comment by johnty** [comment]
oops commented on the wrong library. please delete/close
